# Generated by Django 5.2.4 on 2025-07-18 23:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('yearName', models.CharField(max_length=10)),
                ('yearId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nameAr', models.CharField(max_length=200)),
                ('nameEn', models.CharField(max_length=200)),
                ('studentId', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('level', models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('earnedHours', models.SmallIntegerField(blank=True, default=0)),
                ('nationalId', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)])),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated')], default='active', max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dateOfBirth', models.DateField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseName', models.CharField(max_length=200)),
                ('courseCode', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('credits', models.SmallIntegerField(default=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.SmallIntegerField(blank=True, default=0)),
                ('type', models.CharField(blank=True, choices=[('core', 'Core'), ('specialization', 'Specialization')], default='core', max_length=15)),
                ('prerequisites', models.ManyToManyField(blank=True, to='betterAPI.course')),
            ],
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('nameAr', models.CharField(max_length=200)),
                ('nameEn', models.CharField(max_length=200)),
                ('nationalId', models.CharField(max_length=14, unique=True)),
                ('educatorId', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('Teaching Assistant', 'Teaching Assistant'), ('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], default='Lecturer', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educators', to='betterAPI.department')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterId', models.AutoField(primary_key=True, serialize=False)),
                ('semesterName', models.CharField(blank=True, choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], default='fall', max_length=10, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('registeredHours', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('earnedHours', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('academicYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='betterAPI.academicyear')),
                ('courses', models.ManyToManyField(blank=True, related_name='semesters', to='betterAPI.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterGrade', models.CharField(blank=True, max_length=2, null=True)),
                ('numericGrade', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('courseworkMax', models.SmallIntegerField(blank=True, default=50, null=True)),
                ('coursework', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('examMax', models.SmallIntegerField(blank=True, default=50, null=True)),
                ('exam', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('total', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='betterAPI.course')),
                ('educator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='betterAPI.educator')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='betterAPI.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='betterAPI.student')),
            ],
        ),
        migrations.AddField(
            model_name='academicyear',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='betterAPI.student'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionType', models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab'), ('TUT', 'Tutorial')], default='LEC', max_length=3)),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday')])),
                ('startPeriod', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('endPeriod', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('location', models.CharField(blank=True, help_text="e.g., 'Room 301' or 'Online'", max_length=100, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='betterAPI.enrollment')),
            ],
        ),
    ]
