# Generated by Django 5.2.4 on 2025-07-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='homePhone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
