# Generated by Django 5.2.4 on 2025-07-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='type',
            field=models.CharField(choices=[('Teaching Assistant', 'Teaching Assistant'), ('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], default='Lecturer', max_length=30),
        ),
    ]
