# Generated by Django 5.2.5 on 2025-09-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterAPI', '0002_student_gender_student_homephone_student_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_academic_year', models.CharField(help_text="e.g., '2024-2025'", max_length=10)),
                ('current_semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], default='fall', max_length=10)),
                ('registration_open', models.BooleanField(default=False, help_text='Is registration currently open?')),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('course', 'level', 'group_number')},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='semester',
        ),
    ]
