# Generated by Django 5.2.4 on 2025-07-18 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterAPI', '0002_educator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationalId',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxValueValidator(14)]),
        ),
    ]
