# Generated by Django 5.2.5 on 2025-09-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterAPI', '0003_add_global_settings_remove_semester_from_registration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('course', 'group_number')},
        ),
        migrations.AlterField(
            model_name='registration',
            name='capacity',
            field=models.PositiveIntegerField(default=60, help_text='Total capacity for this course group'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='group_number',
            field=models.PositiveIntegerField(help_text='Group number for this course (1, 2, 3, etc.)'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='capacity',
            field=models.PositiveIntegerField(default=30, help_text='Capacity for this specific section (should be <= registration capacity)'),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='level',
        ),
    ]
