# Generated by Django 5.2.5 on 2025-09-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterAPI', '0004_remove_redundant_level_from_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='degrees',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='homePhone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
